## Cropped size
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 100
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 90
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 80
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 70
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 60
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 40
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 30
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 20
python repo/main.py --model_type prompt_vit6_3  --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/shuffle_data/data6 --_use_wandb --group_name AB_IS_shuffle_data6 --seed 79 --body_model_name vit --image_size 10
