

python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 50 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 60 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 70 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 90 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 100 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 40 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 30 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data/data2 --_use_wandb --group_name BasedYear_Data2_1days --seed 79 --body_model_name vit --image_size 20 --max_lead_time 12 --historical_data_length 64


