python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 2
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 4
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 8
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 12
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 16
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 20
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 24
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 28
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 32
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 36
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 40
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 44
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 48
python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64


python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 50 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 60 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 70 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 90 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 100 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 40 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 30 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data0 --_use_wandb --group_name BasedYear_Data0_3days --seed 79 --body_model_name vit --image_size 20 --max_lead_time 12 --historical_data_length 64


python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /mnt/disk1/aiotlab/longnd/data/tc_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 50 --max_lead_time 12 --historical_data_length 64 --use_position_embedding
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /mnt/disk1/aiotlab/longnd/data/tc_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 50 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 60 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 70 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 90 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 100 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 40 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 30 --max_lead_time 12 --historical_data_length 64
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data2 --_use_wandb --group_name BasedYear_Data2_3days --seed 79 --body_model_name vit --image_size 20 --max_lead_time 12 --historical_data_length 64
