# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 1
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 2
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 4
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 8
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 12
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 16
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 20
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 24
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 28
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 32
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 36
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 40
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 44
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 48
# python repo/main.py --model_type prompt_vit6_5 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64


python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 4 --patch_size_h 10 --patch_size_w 10
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 5 --patch_size_h 10 --patch_size_w 10
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 6 --patch_size_h 10 --patch_size_w 10
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 7 --patch_size_h 10 --patch_size_w 10
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 8 --patch_size_h 10 --patch_size_w 10
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 9 --patch_size_h 10 --patch_size_w 10
python repo/main.py --model_type prompt_vit6_6 --batch_size 32 --lr 1e-5 --epochs 1000 --patience 10 --data_dir /home/user01/aiotlab/longnd/cyclone_prediction/raw_data/basedyear_data_3days/data3 --_use_wandb --group_name BasedYear_Data3_3days --seed 79 --body_model_name vit --image_size 80 --max_lead_time 12 --historical_data_length 64 --patch_size_t 10 --patch_size_h 10 --patch_size_w 10
